-- FAKE DEVELOPMENT DATA ONLY. Delete with: delete from public.listings where slug like 'demo-%';
insert into public.listings(category,title,title_hi,slug,description,description_hi,locality,full_address,latitude,longitude,distance_to_vishnupad_km,status,is_verified,featured,sort_order) values
('stay','Sangam Demo Guest House','संगम डेमो गेस्ट हाउस','demo-sangam-guest-house','FAKE SAMPLE — not a real property.','डेमो डेटा — वास्तविक संपत्ति नहीं।','Vishnupad','Demo Road, Gaya',24.7914,85.0002,0.8,'draft',true,true,1),
('stay','Pitru Demo Lodge','पितृ डेमो लॉज','demo-pitru-lodge','FAKE SAMPLE — not a real property.','डेमो डेटा — वास्तविक संपत्ति नहीं।','Tekari Road','Demo Lane, Gaya',24.78,84.99,2.1,'draft',false,false,2),
('stay','Yatra Demo Dharamshala','यात्रा डेमो धर्मशाला','demo-yatra-dharamshala','FAKE SAMPLE — not a real property.','डेमो डेटा — वास्तविक संपत्ति नहीं।','Manpur','Demo Street, Gaya',24.77,85.01,3.2,'draft',true,false,3),
('panda','Demo Pandit Arun','डेमो पंडित अरुण','demo-pandit-arun','FAKE SAMPLE — not a real person.','डेमो डेटा — वास्तविक व्यक्ति नहीं।','Vishnupad','Demo Address, Gaya',24.79,85,0.5,'draft',true,false,4),
('panda','Demo Pandit Meera','डेमो पंडित मीरा','demo-pandit-meera','FAKE SAMPLE — not a real person.','डेमो डेटा — वास्तविक व्यक्ति नहीं।','Ramshila','Demo Address, Gaya',24.8,84.98,1.8,'draft',true,false,5),
('panda','Demo Pandit Ravi','डेमो पंडित रवि','demo-pandit-ravi','FAKE SAMPLE — not a real person.','डेमो डेटा — वास्तविक व्यक्ति नहीं।','Pretshila','Demo Address, Gaya',24.79,85.02,2.3,'draft',false,false,6),
('food','Demo Bhojanalay A','डेमो भोजनालय A','demo-food-a','FAKE SAMPLE.','डेमो डेटा।','Vishnupad','Demo Address, Gaya',24.79,85,1,'published',true,false,7),
('food','Demo Bhojanalay B','डेमो भोजनालय B','demo-food-b','FAKE SAMPLE.','डेमो डेटा।','Station Road','Demo Address, Gaya',24.8,85.01,2,'published',false,false,8),
('transport','Demo E-Rickshaw Service','डेमो ई-रिक्शा सेवा','demo-transport','FAKE SAMPLE.','डेमो डेटा।','Gaya','Demo Address, Gaya',24.79,85,1.2,'published',true,false,9),
('transport','Demo Tempo Traveller','डेमो टेम्पो ट्रैवलर','demo-tempo','FAKE SAMPLE.','डेमो डेटा।','Gaya','Demo Address, Gaya',24.78,85,2.2,'published',false,false,10),
('shop','Demo Puja Samagri','डेमो पूजा सामग्री','demo-shop','FAKE SAMPLE.','डेमो डेटा।','Vishnupad','Demo Address, Gaya',24.79,85,0.7,'published',true,false,11),
('guide','Demo Local Guide','डेमो स्थानीय गाइड','demo-guide','FAKE SAMPLE.','डेमो डेटा।','Gaya','Demo Address, Gaya',24.79,85,1.4,'published',true,false,12),
('other','Demo Wheelchair Help','डेमो व्हीलचेयर सहायता','demo-other','FAKE SAMPLE.','डेमो डेटा।','Gaya','Demo Address, Gaya',24.79,85,1.6,'published',false,false,13);

insert into public.stay_details(listing_id,property_type,amenities,elderly_friendly) select id,'guest house','["wifi","ground-floor","attached-bathroom"]',true from public.listings where slug='demo-sangam-guest-house';
insert into public.stay_details(listing_id,property_type,amenities,elderly_friendly) select id,'lodge','["hot-water","parking"]',false from public.listings where slug='demo-pitru-lodge';
insert into public.stay_details(listing_id,property_type,amenities,elderly_friendly) select id,'dharamshala','["ground-floor","food"]',true from public.listings where slug='demo-yatra-dharamshala';

insert into public.stay_rooms(listing_id,room_type_name,ac,capacity,beds,normal_price_per_night,mela_price_per_night,availability_status) select id,'Demo AC Double',true,2,1,900,1400,'available' from public.listings where slug='demo-sangam-guest-house';
insert into public.stay_rooms(listing_id,room_type_name,ac,capacity,beds,normal_price_per_night,mela_price_per_night,availability_status) select id,'Demo Non-AC Double',false,2,1,600,1000,'available' from public.listings where slug='demo-pitru-lodge';
insert into public.stay_rooms(listing_id,room_type_name,ac,capacity,beds,normal_price_per_night,mela_price_per_night,availability_status) select id,'Demo Family Room',false,4,2,800,1200,'limited' from public.listings where slug='demo-yatra-dharamshala';

insert into public.listing_images(listing_id,storage_path,public_url,alt_text,sort_order,is_cover) select id,'demo/stay-1-1.jpg','https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80','FAKE demo image',1,true from public.listings where slug='demo-sangam-guest-house';
insert into public.listing_images(listing_id,storage_path,public_url,alt_text,sort_order,is_cover) select id,'demo/stay-1-2.jpg','https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=1200&q=80','FAKE demo image',2,false from public.listings where slug='demo-sangam-guest-house';
insert into public.listing_images(listing_id,storage_path,public_url,alt_text,sort_order,is_cover) select id,'demo/stay-1-3.jpg','https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1200&q=80','FAKE demo image',3,false from public.listings where slug='demo-sangam-guest-house';
insert into public.listing_images(listing_id,storage_path,public_url,alt_text,sort_order,is_cover) select id,'demo/stay-2-1.jpg','https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&w=1200&q=80','FAKE demo image',1,true from public.listings where slug='demo-pitru-lodge';
insert into public.listing_images(listing_id,storage_path,public_url,alt_text,sort_order,is_cover) select id,'demo/stay-2-2.jpg','https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=1200&q=80','FAKE demo image',2,false from public.listings where slug='demo-pitru-lodge';
insert into public.listing_images(listing_id,storage_path,public_url,alt_text,sort_order,is_cover) select id,'demo/stay-2-3.jpg','https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=1200&q=80','FAKE demo image',3,false from public.listings where slug='demo-pitru-lodge';
insert into public.listing_images(listing_id,storage_path,public_url,alt_text,sort_order,is_cover) select id,'demo/stay-3-1.jpg','https://images.unsplash.com/photo-1564501049412-61c2a3083791?auto=format&fit=crop&w=1200&q=80','FAKE demo image',1,true from public.listings where slug='demo-yatra-dharamshala';
insert into public.listing_images(listing_id,storage_path,public_url,alt_text,sort_order,is_cover) select id,'demo/stay-3-2.jpg','https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1200&q=80','FAKE demo image',2,false from public.listings where slug='demo-yatra-dharamshala';
insert into public.listing_images(listing_id,storage_path,public_url,alt_text,sort_order,is_cover) select id,'demo/stay-3-3.jpg','https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80','FAKE demo image',3,false from public.listings where slug='demo-yatra-dharamshala';

insert into public.panda_details(listing_id,full_name,short_bio,years_experience,languages,brahmin_sub_group,rituals,dakshina_min,dakshina_max,consent_obtained,face_image_path) select id,'Demo Pandit Arun','FAKE SAMPLE — not a real person.',12,'["Hindi","Bhojpuri"]','Gayawal','["Pind Daan 1-day","Tarpan","Shraddha"]',1100,2500,true,'demo-face-arun.webp' from public.listings where slug='demo-pandit-arun';
insert into public.panda_details(listing_id,full_name,short_bio,years_experience,languages,brahmin_sub_group,rituals,dakshina_min,dakshina_max,consent_obtained,face_image_path) select id,'Demo Pandit Meera','FAKE SAMPLE — not a real person.',8,'["Hindi","Maithili"]','Maithil','["Pind Daan 3-day","Akshayavat Shraddha"]',1500,3000,true,'demo-face-meera.webp' from public.listings where slug='demo-pandit-meera';
insert into public.panda_details(listing_id,full_name,short_bio,years_experience,languages,brahmin_sub_group,rituals,dakshina_min,dakshina_max,consent_obtained,face_image_path) select id,'Demo Pandit Ravi','FAKE SAMPLE — not a real person.',5,'["Hindi","Bengali"]','Kanyakubja','["Pind Daan 1-day","Brahmin Bhojan"]',1000,2200,true,'demo-face-ravi.webp' from public.listings where slug='demo-pandit-ravi';

insert into public.food_details(listing_id,food_type,price_per_thali,timings,capacity,home_delivery,bulk_orders,brahmin_bhojan) select id,'pure veg',120,'11:00-15:00',60,true,true,true from public.listings where slug='demo-food-a';
insert into public.food_details(listing_id,food_type,price_per_thali,timings,capacity,home_delivery,bulk_orders,brahmin_bhojan) select id,'sattvic',150,'10:00-16:00',80,false,true,true from public.listings where slug='demo-food-b';
insert into public.transport_details(listing_id,vehicle_type,capacity,ac,pricing_basis,rate,station_airport_pickup,outstation,driver_name,languages) select id,'e-rickshaw',4,false,'fixed local route',150,true,false,'Demo Driver','["Hindi"]' from public.listings where slug='demo-transport';
insert into public.transport_details(listing_id,vehicle_type,capacity,ac,pricing_basis,rate,station_airport_pickup,outstation,driver_name,languages) select id,'tempo traveller',12,true,'per km',24,true,true,'Demo Driver','["Hindi","English"]' from public.listings where slug='demo-tempo';
insert into public.shop_details(listing_id,items,pind_daan_kit_price,packages,bulk_orders,home_delivery,opening_hours) select id,'["pind daan kit","samagri"]',250,'FAKE package',true,true,'08:00-20:00' from public.listings where slug='demo-shop';
insert into public.guide_details(listing_id,languages,experience_years,fee_half_day,fee_day,specialties,government_certified) select id,'["Hindi","English"]',6,700,1200,'["Gaya","Bodh Gaya","rituals guidance"]',false from public.listings where slug='demo-guide';
insert into public.other_details(listing_id,sub_type,extra_fields) select id,'wheelchair-help','{"demo":true}' from public.listings where slug='demo-other';

insert into public.listing_contacts(listing_id,phone,whatsapp) select id,'9999999999','9999999999' from public.listings;
update public.listings set status='published' where slug like 'demo-%';
